# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(797, 705)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, -20, 791, 721))
        self.frame.setStyleSheet("background-color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, -80, 721, 811))
        self.label.setStyleSheet("image: url(:/newPrefix/geeks-2894621__340.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalWidget_2.setGeometry(QtCore.QRect(330, 210, 201, 191))
        self.verticalWidget_2.setStyleSheet("background-color:rgba(255, 255, 255, 100);")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_6.setStyleSheet("image: url(:/newPrefix/user-interface.png);\n"
"background-color:rgba(255, 255, 255, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.lineEdit_4.setStyleSheet("border : 0px;\n"
"border-bottom : 1px solid;\n"
"background-color:rgba(255, 255, 255, 0);\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.lineEdit_5.setStyleSheet("border : 0px;\n"
"border-bottom : 1px solid;\n"
"background-color:rgba(255, 255, 255, 0);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.lineEdit_6.setStyleSheet("border : 0px;\n"
"border-bottom : 1px solid;\n"
"background-color:rgba(255, 255, 255, 0);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalWidget_2)
        self.checkBox_2.setStyleSheet("background-color:rgba(255, 255, 255, 0);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 410, 201, 28))
        self.pushButton_2.setStyleSheet("border-radius:6px;\n"
"background-color:rgb(19, 145, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"font-weight: 500;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(400, 470, 301, 20))
        self.label_5.setStyleSheet("background-color:rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-size: 15px;\n"
"font-weight: 500;")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_4.setText(_translate("Form", "Email"))
        self.lineEdit_5.setText(_translate("Form", "Password"))
        self.lineEdit_6.setText(_translate("Form", "Confirm Password"))
        self.checkBox_2.setText(_translate("Form", "Show Password"))
        self.pushButton_2.setText(_translate("Form", "Register"))
        self.label_5.setText(_translate("Form", "Developed by Aditya Nugraha Novianto"))
import 123_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
